---
- name: teampass playbook
  hosts: ansible_client
  remote_user: ec2-user
  become: true
  tasks:

         - name: set required permission
           file:
                        path: /var/www/html/teampass/
                        state: directory
                        owner: www-data
                        group: www-data
                        recurse: yes
                        mode: '0775'
                        
